import type { Metadata } from "next"
import Image from "next/image"
import { Orbitron, Lexend_Deca } from "next/font/google";
import '@/app/globals.css'

export const lexend = Lexend_Deca({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

export const orbitron = Orbitron({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-orbitron",
});

export const metadata: Metadata = {
  title: "Home page - Zene Magazine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={ `${orbitron.variable} ${lexend.variable}` }
    >
      <body className="font-orbitron">
        <div className='min-h-full flex flex-col'>
        <header className="flex justify-end backdrop-blur-xs">
              <Image
                src={'/logos/zenelogo.png'}
                width={200}
                height={100}
                alt={'Zene Logo'}
                className='w-auto h-auto'
              ></Image> 
        </header>
        <hr />
        {children}
        <hr />
        <div className="backdrop-blur-xs">
          <footer className="flex justify-center shrink-0 mt-5 mb-5 text-shadow-lg/50">
            <p>Zene Magazine &copy; 2026</p>
          </footer>
          </div>
          </div>
      </body>
    </html>
  );
}
