import type { Metadata } from "next"
import Image from "next/image"
import '@/app/globals.css'
import { orbitron, lexend} from '@/app/styles/fonts'

const fonts = [orbitron, lexend];

export const metadata: Metadata = {
  title: "Home page - Zene Magazine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fonts[0].variable} ${fonts[1].variable}`}
    >
      <body className="font-orbitron">
        <div className='min-h-full flex flex-col'>
        <header className="flex justify-end backdrop-blur-xs">
              <Image
                src={'/logos/zenelogo.png'}
                width={200}
                height={100}
                alt={'Zene Logo'}
                className='w-auto h-auto'
              ></Image> 
        </header>
        <hr />
        {children}
        <hr />
        <div className="backdrop-blur-xs">
          <footer className="flex justify-center shrink-0 mt-5 mb-5 text-shadow-lg/50">
            <h3>Zene Magazine &copy; 2026</h3>
          </footer>
          </div>
          </div>
      </body>
    </html>
  );
}
