import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Home page - Zene Magazine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
